### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by olividir** [KmolYuan/pyslvs#3]
[pyslvs.txt](https://github.com/KmolYuan/pyslvs/files/10969537/pyslvs.txt)
**Describe the bug**
Can't install pyslvs
**To Reproduce**
1. Write   'pip install pyslvs`
pip fetches some things, but I get the error 
```
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          with gil:
              k = zeros(len(path) - 2, dtype=f64)
          cdef int i
          for i in range(len(path) - 2):
              k[i] = ((p1d[i, 0] * p2d[i, 1] - p2d[i, 0] * p1d[i, 1])
                      / (p1d[i, 0] * p1d[i, 0] + p1d[i, 1] * p1d[i, 1]) ** 1.5)
                      ^
      ------------------------------------------------------------
      
      pyslvs/optimization/f_planar.pyx:123:16: Calling gil-requiring function not allowed without gil
      Compiling pyslvs/optimization/f_planar.pyx because it changed.
      [1/1] Cythonizing pyslvs/optimization/f_planar.pyx
      Traceback (most recent call last):
        File "/home/olividir/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/olividir/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/olividir/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, local
[pyslvs.txt](https://github.com/KmolYuan/pyslvs/files/10969524/pyslvs.txt)
s())
        File "<string>", line 79, in <module>
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 76, in build_extensions
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-24dsq8kk/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-24dsq8kk/normal/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 122, in build_extension
          new_ext = cythonize(
        File "/tmp/pip-build-env-24dsq8kk/normal/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-24dsq8kk/normal/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyslvs/optimization/f_planar.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyslvs
Failed to build pyslvs
ERROR: Could not build wheels for pyslvs, which is required to install pyproject.toml-based projects
```

**Expected behavior**
Expected the program to install

**Screenshots**
See code above

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Newest :)
 - pip verion 23.0.1

**Additional context**
Full installation process with errors from terminal in external txt file.

**Comment by olividir** [comment]
Managed to install version 1.0.3  manylinux from here https://pypi.tuna.tsinghua.edu.cn/simple/py-slvs/
So this is resolved.
